### ISSUE TITLE
Consider publishing a release with "Add preserving local and external references #30" included

### ISSUE THREAD

**Issue by thyming** [AndersDJohnson/jackson-json-reference#32]
Hi, thanks for your work on this project. It's useful for me to build a directory tree of swagger yaml fragments into a single swagger.yaml file, but the feature contributed in https://github.com/AndersDJohnson/jackson-json-reference/commit/1351309c4be896f0970b20057e72b83c306d666a seems to be critical to making this work perfectly. I'm currently referencing a jitpack maven repo to get a build with this commit, but would you consider publishing a release with this feature?
Thanks!

**Comment by AndersDJohnson** [comment]
@thyming I have begun a publish a new `0.3.0` version to Maven Central. I believe I'm still waiting for the cache to clear, but check here soon: https://search.maven.org/#search%7Cga%7C1%7Cjackson-json-reference. The new release JARs are already on GitHub at: https://github.com/AndersDJohnson/jackson-json-reference/releases/tag/0.3.0. Let me know if something goes wrong, as I haven't manually tested this project and the release process for a while.

**Comment by thyming** [comment]
Thanks so much for this and the project!

**Comment by AndersDJohnson** [comment]
@thyming Please star to express support, and thanks!
