### ISSUE TITLE
References in Arrays are resolved in wrong indexes

### ISSUE THREAD

**Issue by splaw88** [AndersDJohnson/jackson-json-reference#34]
Hi,

there is an issue when putting reference in some element of an Array. 
For example: 
given json test.json: 
`[{"test": "0"},{"$ref": "external.json"},{"test": "2"}]`
and external.json:
`{"test": "1"}`
results with:
`[{"test": "1"},{"$ref": "external.json"},{"test": "2"}]`

external json is resolved in first index of array and reference is still there 
Is this resolvable, or in array there is some other way to place references?

**Comment by AndersDJohnson** [comment]
Resolved by #35.
